name: ElezioniDirettivo
description: A Dart app used to manage directive election at Trento CUS
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular2: 2.0.0-beta.21
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1
  dartdoc:
transformers:
- angular2:
    entry_points: web/main.dart
- dart_to_js_script_rewriter
